# SPDX-FileCopyrightText: 2024-2026 Shaznay Sison
# SPDX-License-Identifier: MIT

"""Docs service — orchestrates manifest loading and all Phase 2 validators."""

from pathlib import Path

from grain.adapters.manifest import load_manifest
from grain.cli.output import CommandResult
from grain.domain.documents import DocumentRecord, build_registry
from grain.domain.errors import ForgeError
from grain.validators.authority_validator import validate_authority
from grain.validators.doc_existence_validator import validate_doc_existence
from grain.validators.manifest_validator import validate_manifest_schema


def validate_docs(root: Path) -> CommandResult:
    """Run all documentation validators against the repository at `root`.

    Steps:
    1. Load docs_manifest.yaml
    2. Validate manifest schema
    3. Build document registry
    4. Validate document existence
    5. Validate authority constraints

    Returns:
        CommandResult with ok=True when all checks pass, ok=False with
        errors populated when any check fails.
    """
    errors: list[str] = []

    # Step 1 — load manifest
    try:
        manifest = load_manifest(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs validate",
            repo=str(root),
            errors=[exc.message],
        )

    # Step 2 — schema validation
    schema_errors = validate_manifest_schema(manifest)
    errors.extend(schema_errors)

    # Steps 3-5 — only proceed if schema is valid (registry requires well-formed manifest)
    if not schema_errors:
        registry = build_registry(manifest)
        errors.extend(validate_doc_existence(registry, root))
        errors.extend(validate_authority(registry, manifest))

    return CommandResult(
        ok=len(errors) == 0,
        command="docs validate",
        repo=str(root),
        errors=errors,
    )


def generate_index(root: Path, dry_run: bool = False) -> CommandResult:
    """Generate or refresh docs/runtime/docs_index.md from the manifest registry.

    Manifest is the authoritative source. The index is derived output.

    Args:
        root: Repository root path.
        dry_run: If True, return the generated content without writing.

    Returns:
        CommandResult with ok=True on success.
    """
    try:
        content, line_count = _render_index(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs index",
            repo=str(root),
            errors=[exc.message],
        )

    index_path = root / "docs" / "runtime" / "docs_index.md"

    if dry_run:
        return CommandResult(
            ok=True,
            command="docs index",
            repo=str(root),
            warnings=[f"dry-run: would write {line_count} lines to {index_path}"],
        )

    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content, encoding="utf-8")
    return CommandResult(
        ok=True,
        command="docs index",
        repo=str(root),
        files_updated=[str(index_path.relative_to(root))],
    )


def refresh_index(root: Path) -> bool:
    """Best-effort incremental refresh of the derived docs_index.md.

    The registry/index is DERIVED, never authored: every ``grain docs`` command
    calls this before answering (unless ``--no-refresh``). Writes only when the
    rendered content actually changed; never raises — a repo without a manifest
    simply skips the refresh.

    Returns True when the index file was (re)written.
    """
    try:
        content, _ = _render_index(root)
    except Exception:
        return False
    index_path = root / "docs" / "runtime" / "docs_index.md"
    try:
        existing = index_path.read_text(encoding="utf-8") if index_path.exists() else None
        if existing == content:
            return False
        index_path.parent.mkdir(parents=True, exist_ok=True)
        index_path.write_text(content, encoding="utf-8")
        return True
    except OSError:
        return False


def _render_index(root: Path) -> tuple[str, int]:
    """Render the docs index content. Raises ForgeError when the manifest is
    missing or invalid."""
    manifest = load_manifest(root)
    registry = build_registry(manifest)
    authority_order = manifest.get("rules", {}).get("authority_order", [])

    lines: list[str] = []
    lines.append("# Docs Index")
    lines.append("")
    lines.append("> Generated by `grain docs index` from `docs/runtime/docs_manifest.yaml`.")
    lines.append("> Do not edit manually — rerun `grain docs index` to refresh.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Authority Order")
    lines.append("")
    for i, entry in enumerate(authority_order, 1):
        lines.append(f"{i}. `{entry}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    for layer in ("canonical", "working", "runtime"):
        records = registry.by_layer(layer)
        if not records:
            continue
        lines.append(f"## {layer.capitalize()} Docs")
        lines.append("")
        lines.append("| ID | Path | Authority | Editable by Agents | Purpose |")
        lines.append("|----|----|----|----|-----|")
        for r in records:
            lines.append(
                f"| `{r.id}` | `{r.path}` | {r.authority} "
                f"| {'yes' if r.editable_by_agents else 'no'} | {r.purpose} |"
            )
        lines.append("")

    lines.extend(_render_doc_health(root, manifest))

    content = "\n".join(lines)
    return content, len(lines)


def _render_doc_health(root: Path, manifest: dict) -> list[str]:
    """Derived Doc Health section: verified dates + staleness badges.

    Appended after the classic tables so existing consumers of the index keep
    their format untouched. Badges are computed FRESH from the current repo
    state at render time (verification stamps + cited-path existence) — never
    replayed from a previous audit's verdicts.
    """
    from datetime import date

    from grain.services.docs_corpus import external_roots_from_manifest, load_corpus

    corpus = [
        d for d in load_corpus(root, manifest=manifest, use_cache=True)
        if d.layer in ("canonical", "working") and not d.root_name
    ]
    if not corpus:
        return []

    ext_roots = dict(external_roots_from_manifest(root, manifest))

    def _target_exists(target: str) -> bool:
        if (root / target).exists():
            return True
        head, _, tail = target.partition("/")
        return bool(tail) and head in ext_roots and (ext_roots[head] / tail).exists()

    thresholds = manifest.get("audit_thresholds") or {}
    try:
        unverified_days = int(thresholds.get("canon_unverified_days", 90))
    except (TypeError, ValueError):
        unverified_days = 90
    today = date.today()

    lines: list[str] = []
    lines.append("---")
    lines.append("")
    lines.append("## Doc Health")
    lines.append("")
    lines.append("> Derived — refreshed by `grain docs` commands. Full signals: `grain docs audit`.")
    lines.append("")
    lines.append("| Path | Layer | Modified | Last-verified | Badges |")
    lines.append("|----|----|----|----|----|")

    order = {"canonical": 0, "working": 1}
    for doc in sorted(corpus, key=lambda d: (order.get(d.layer, 9), d.rel_path)):
        badges: list[str] = []
        if doc.is_tombstone:
            badges.append("TOMBSTONE")
        else:
            missing = [
                t
                for t in dict.fromkeys(list(doc.resolved_links) + list(doc.path_refs))
                if t and not _target_exists(t)
            ]
            if missing:
                badges.append(f"ROT:{len(missing)}")
            if doc.layer == "canonical" and unverified_days > 0:
                if doc.last_verified is not None:
                    if (today - doc.last_verified).days > unverified_days:
                        badges.append("UNVERIFIED")
                elif (
                    doc.last_modified is not None
                    and (today - doc.last_modified.date()).days > unverified_days
                ):
                    badges.append("UNVERIFIED")
        modified = doc.last_modified.date().isoformat() if doc.last_modified else "—"
        verified = doc.last_verified.isoformat() if doc.last_verified else "never"
        lines.append(
            f"| `{doc.rel_path}` | {doc.layer} | {modified} | {verified} "
            f"| {' '.join(badges) if badges else '—'} |"
        )
    lines.append("")
    return lines


def show_doc(root: Path, doc_id: str) -> tuple[CommandResult, DocumentRecord | None]:
    """Look up a single document by ID from the manifest registry.

    Returns a tuple of (CommandResult, DocumentRecord | None).
    CommandResult.ok is False when the manifest cannot be loaded or the doc
    is not found. The record is None on failure.
    """
    try:
        manifest = load_manifest(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs show",
            repo=str(root),
            errors=[exc.message],
        ), None

    registry = build_registry(manifest)
    record = registry.by_id(doc_id)

    if record is None:
        return CommandResult(
            ok=False,
            command="docs show",
            repo=str(root),
            errors=[f"Doc '{doc_id}' not found in manifest"],
        ), None

    return CommandResult(
        ok=True,
        command="docs show",
        repo=str(root),
    ), record
